name: My Workflow
on: [push]

# ✅ CORRECT: 'jobs:' is the required top-level key
jobs:
  my_job_name: # You define one or more jobs here
    runs-on: ubuntu-latest
    
    # ✅ CORRECT: 'services:' is now *inside* the job
    services:
      my-service:
        image: my-image:latest
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      - name: Run my build
        run: echo "Connecting to my-service..."
