# ==========================================
# Render.com - Deploy do Coletor App (Flet)
# Projeto: ControleDatas / coletorApp
# ==========================================

services:
  - type: web
    name: coletor-app
    env: docker
    region: oregon  # ou use "frankfurt" se quiser servidor na Europa

    # Caminhos relativos à raiz do repositório GitHub
    dockerfilePath: ./coletorApp/Dockerfile
    dockerContext: ./coletorApp

    # Configurações de porta (Render define automaticamente $PORT)
    envVars:
      - key: PORT
        value: 8080
      - key: FLET_DISPLAY
        value: false

    # Caminho de health check (opcional)
    healthCheckPath: /healthz

    # Política de auto-deploy
    autoDeploy: true

    # Comando opcional para rodar antes do app (ex: migrações de banco)
    preDeployCommand: ""

    # Tempo máximo para o Render considerar o serviço "healthy"
    plan: free  # Pode ser 'starter' se quiser mais performance

    # Diretórios de cache (para builds mais rápidos)
    disk:
      name: coletor-data
      mountPath: /app/data
      sizeGB: 1
